CREATE TABLE IF NOT EXISTS dialer (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  host VARCHAR(50) NOT NULL,
  port INT UNSIGNED NOT NULL,
  from_name VARCHAR(50) NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  hash_salt INT,
  access_token VARCHAR(50) NOT NULL
)
